In [1]:
from pflacco.classical_ela_features import *
from pflacco.sampling import create_initial_sample
from ioh import get_problem, ProblemClass
import pandas as pd

features = []
# Get all 24 single-objective noiseless BBOB function in dimension 2 and 3 for the first five instances.
for fid in range(1,25):
    for dim in [2, 3]:
        for iid in range(1, 6):
            # Get optimization problem
            problem = get_problem(fid, iid, dim, ProblemClass.BBOB)

            # Create sample
            X = create_initial_sample(dim, lower_bound = -5, upper_bound = 5)
            y = X.apply(lambda x: problem(x), axis = 1)

            # Calculate ELA features
            ela_meta = calculate_ela_meta(X, y)
            ela_distr = calculate_ela_distribution(X, y)
            ela_level = calculate_ela_level(X, y)
            nbc = calculate_nbc(X, y)
            disp = calculate_dispersion(X, y)
            ic = calculate_information_content(X, y, seed = 100)

            # Store results in pandas dataframe
            data = pd.DataFrame({**ic, **ela_meta, **ela_distr, **nbc, **disp, **{'fid': fid}, **{'dim': dim}, **{'iid': iid}}, index = [0])
            features.append(data)

features = pd.concat(features).reset_index(drop = True)

c:\Users\kyana\AppData\Local\Programs\Python\Python311\Lib\site-packages\pflacco\classical_ela_features.py:108: RuntimeWarning: divide by zero encountered in scalar divide
  quad_simple_cond = quad_model_con_max/quad_model_con_min
c:\Users\kyana\AppData\Local\Programs\Python\Python311\Lib\site-packages\pflacco\classical_ela_features.py:1347: RuntimeWarning: divide by zero encountered in scalar divide
  lda_qda = np.array([lda_mmce[i]/qda_mmce[i] for i in range(len(ela_level_quantiles))])
c:\Users\kyana\AppData\Local\Programs\Python\Python311\Lib\site-packages\pflacco\classical_ela_features.py:108: RuntimeWarning: divide by zero encountered in scalar divide
  quad_simple_cond = quad_model_con_max/quad_model_con_min
c:\Users\kyana\AppData\Local\Programs\Python\Python311\Lib\site-packages\pflacco\classical_ela_features.py:108: RuntimeWarning: divide by zero encountered in scalar divide
  quad_simple_cond = quad_model_con_max/quad_model_con_min
c:\Users\kyana\AppData\Local\Programs\Python\Python311\Lib\site-packages\pflacco\classical_ela_features.py:108: RuntimeWarning: divide by zero encountered in scalar divide
  quad_simple_cond = quad_model_con_max/quad_model_con_min

In [12]:
features

,ic.h_max,ic.eps_s,ic.eps_max,ic.eps_ratio,ic.m0,ic.costs_runtime,ela_meta.lin_simple.adj_r2,ela_meta.lin_simple.intercept,ela_meta.lin_simple.coef.min,ela_meta.lin_simple.coef.max,...,disp.diff_mean_10,disp.diff_mean_25,disp.diff_median_02,disp.diff_median_05,disp.diff_median_10,disp.diff_median_25,disp.costs_runtime,fid,dim,iid
0,0.723599,1.086086,1.885344,0.705706,0.367347,0.171,0.279031,97.583855,0.599222,2.220676,...,-3.667034,-2.796932,-4.663710,-4.340227,-3.582209,-2.740295,0.0,1,2,1
1,0.644577,1.326326,2.920556,0.825826,0.377551,0.156,0.894248,434.733695,5.687876,7.703178,...,-3.495223,-2.674072,-3.812702,-3.837386,-3.484730,-2.391569,0.0,1,2,2
2,0.704600,1.266266,4.849374,0.885886,0.316327,0.172,0.819249,-215.939107,0.499324,7.503178,...,-3.366637,-2.396171,-4.785490,-3.496943,-3.166415,-2.454170,0.0,1,2,3
3,0.735492,1.126126,3.058338,0.585586,0.397959,0.172,0.405030,-133.239068,0.440778,2.940924,...,-3.203519,-2.333507,-4.420605,-4.102743,-2.960040,-2.341476,0.0,1,2,4
4,0.689552,1.226226,4.322659,0.845846,0.357143,0.172,0.825852,4.919127,1.363324,7.322422,...,-3.763408,-2.657949,-4.087822,-3.895932,-3.593211,-2.651589,0.0,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,0.874820,1.686687,5.968856,0.985986,0.614865,0.204,0.222604,174.239124,2.054202,3.240836,...,-2.107950,-1.647262,-0.135781,-2.140374,-2.148556,-1.538556,0.0,24,3,1
236,0.865810,1.726727,7.342870,1.006006,0.662162,0.203,0.298557,167.111563,2.928470,4.179833,...,-2.213537,-1.474474,-1.644860,-1.633762,-2.130875,-1.539990,0.0,24,3,2
237,0.878892,1.766767,8.829700,1.046046,0.716216,0.203,0.331138,83.812737,2.625399,3.178839,...,-1.176162,-1.398975,1.167921,-1.496113,-1.450596,-1.493168,0.0,24,3,3
238,0.872910,1.806807,7.342870,1.026026,0.621622,0.188,0.318526,263.444211,2.409726,3.485210,...,-1.882423,-1.859769,-1.934914,-1.527123,-1.934914,-1.961077,0.0,24,3,4
239,0.878450,1.766767,6.696160,1.026026,0.594595,0.203,0.325189,-63.192295,2.343275,4.128341,...,-2.749833,-1.750532,-3.057669,-2.784100,-2.791434,-1.992633,0.0,24,3,5

In [13]:
features.columns

Index(['ic.h_max', 'ic.eps_s', 'ic.eps_max', 'ic.eps_ratio', 'ic.m0',
       'ic.costs_runtime', 'ela_meta.lin_simple.adj_r2',
       'ela_meta.lin_simple.intercept', 'ela_meta.lin_simple.coef.min',
       'ela_meta.lin_simple.coef.max', 'ela_meta.lin_simple.coef.max_by_min',
       'ela_meta.lin_w_interact.adj_r2', 'ela_meta.quad_simple.adj_r2',
       'ela_meta.quad_simple.cond', 'ela_meta.quad_w_interact.adj_r2',
       'ela_meta.costs_runtime', 'ela_distr.skewness', 'ela_distr.kurtosis',
       'ela_distr.number_of_peaks', 'ela_distr.costs_runtime',
       'nbc.nn_nb.sd_ratio', 'nbc.nn_nb.mean_ratio', 'nbc.nn_nb.cor',
       'nbc.dist_ratio.coeff_var', 'nbc.nb_fitness.cor', 'nbc.costs_runtime',
       'disp.ratio_mean_02', 'disp.ratio_mean_05', 'disp.ratio_mean_10',
       'disp.ratio_mean_25', 'disp.ratio_median_02', 'disp.ratio_median_05',
       'disp.ratio_median_10', 'disp.ratio_median_25', 'disp.diff_mean_02',
       'disp.diff_mean_05', 'disp.diff_mean_10', 'disp.diff_mean_25',
       'disp.diff_median_02', 'disp.diff_median_05', 'disp.diff_median_10',
       'disp.diff_median_25', 'disp.costs_runtime', 'fid', 'dim', 'iid'],
      dtype='object')

In [14]:
X

           x0        x1        x2
0   -0.960762  4.879210 -4.264658
1   -4.428750  1.449433  2.751391
2    4.441674  2.242519  4.286196
3    4.255156 -2.036639  2.826303
4   -4.239683 -0.653469 -0.145121
..        ...       ...       ...
145 -0.762508 -4.454758  0.085164
146 -1.101718  0.522086  1.602270
147 -2.626668  1.315628 -2.731155
148  3.211515  2.487736 -0.540007
149 -2.034729  0.018683 -4.920902

[150 rows x 3 columns]

In [15]:
y

0      -24.360996
1      -52.124160
2        2.476080
3      -80.085112
4      -40.407543
          ...
145    -95.392637
146   -109.630685
147    -60.835438
148    -62.299139
149    -51.186933
Length: 150, dtype: float64